permalink: /:year:month:day/:title
url: himself65.com
baseurl: /project

# variables
name: 扩散性百万甜面包的Blog
description: Hello,world
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true